### ISSUE TITLE
Request moving Summary of Actions to output window

### ISSUE THREAD

**Issue by willasm** [Serhioromano/vscode-gitflow#11]
The summary can be quite long in some cases and it can be difficult to read using the notification window. It would look much nicer to view it in an output window instead. Thanks for the great extension.

**Comment by Serhioromano** [comment]
I have already added this yesterday. So it will be there in new version.

**Comment by Serhioromano** [comment]
I have released version 1.0.0 with this output window. This feature concludes what I wanted to implement in this extension, so it is version 1.0.0.
