### ISSUE TITLE
Potential issue with case for branch folder names

### ISSUE THREAD

**Issue by RaddishIoW** [Serhioromano/vscode-gitflow#15]
I've not yet been able to track down exactly what is happening, but I've had some weirdness with the case of the branch folder names and that affecting whether the branch correctly shows in the "GitFlow" panel of the "Source Control" panel.

If the folder name for the features branch I create is "Features/", it shows in this panel, but doesn't appear to be recognised by Git Flow as a Feature branch. If it's set to "features/" then it shows as a Feature branch for Git Flow purposes (and in GitKraken), but doesn't show in the panel.

I'll try and trace where this might be happening...

I'm on macOS Monterey and the latest git version, and "core.ignorecase" is set to `false` in the global git config.

If you need any more info, I'd be glad to provide.

**Comment by RaddishIoW** [comment]
OK, extra goings-on:

I just tried to Finish a feature and received this error:

> Error executing: git flow feature finish --push job-acknowledgement : Error: Command failed: git flow feature finish --push job-acknowledgement Fatal: Branch 'feature/job-acknowledgement' does not exist and is required.

The branch name _was_ "feature/job-acknowledgement", but after this failed operation it was changed to "Feature/job-acknowledgement"

**Comment by Serhioromano** [comment]
Even if this error is reproducible, I think it is related to git flow extension. I'll make some checks tomorrow.

**Comment by Serhioromano** [comment]
> @RaddishIoW If the folder name for the features branch I create is "Features/",

What do you mean you create branch with `git checkout Features/my-feature`? Or you create with new feature command in Git Flow extension?

**Comment by RaddishIoW** [comment]
I created the Feature using the extension.

**Comment by Serhioromano** [comment]
And you used capital letter Feature when `git init`?

**Comment by Serhioromano** [comment]
I can confirm that capital letter `Feature` cause a lot of different problems. Although command is constructed right way. `git floe feature start new01`. This means that the problem is in git-flow extension of Git in CLI. There is not much I can do about this. I'll add it known issues in README.

**Comment by Serhioromano** [comment]
In my case, when I change configuration for feature branch to Feature, when I create new feature lets say

    git flow feature start new01

in creates new root branch `Featurenew01`

I'll look though code of that extension, because I do not believe it is well supported and see if that could be fixed. As I understand those are just set of bash scripts.
