### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by RaddishIoW** [Serhioromano/vscode-gitflow#16]
- Issue Type: `Performance`
- Extension Name: `vscode-gitflow`
- Extension Version: `1.0.1`
- OS Version: `Darwin x64 21.3.0`
- VS Code version: `1.64.2`

[Serhioromano.vscode-gitflow-unresponsive.cpuprofile.txt](https://github.com/Serhioromano/vscode-gitflow/files/8105166/Serhioromano.vscode-gitflow-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Serhioromano** [comment]
I see. The first tree load takes a lot of time. I'll see what I can do about that.

**Comment by Serhioromano** [comment]
This one was a tough one. I am not an expert on performance optimization. It took me some serious investigations. I think I have improved it like 2x or 3x. Although I believe there is still room for improvement. Anyway, next update later today 1.1.* should work much faster. I'll close this for now, but when you test it and it is still slow, feel free to reopen.

**Comment by Serhioromano** [comment]
Added even few more thing. Version  1.1.0 should be published already.

**Comment by Serhioromano** [comment]
It broke and not working at all now. Quickly try to solve.

**Comment by Serhioromano** [comment]
😵‍💫 finally. Version  1.1.1. I used external library, for that one need a bundler to build an extension. Forsc fine and notable faster.

**Comment by Serhioromano** [comment]
And @RaddishIoW , thank you for review!
