### ISSUE TITLE
Version handling via package.json

### ISSUE THREAD

**Issue by K-Ko** [Serhioromano/vscode-gitflow#19]
It is not clear, how and when the `package.json` of a repo will be updated.

Do I'm missing a setting to "activate" this?

**Comment by Serhioromano** [comment]
It works like this.

1. In your package json you have *.*.* (anything). Let's say `1.0.0`
2. You create a release or hotfix, those are only branches it works for, and you give it a name `1.0.1` for instance.
3. Now when you finish release or hotfix, before process finish command `package.json` will be updated to version `1.0.1`

There is no need to turn it off because, if you update version manually and it matches or name of your branch was not `/^[0-9]+\.[0-9]+\.[0-9]+$/` format nothing will happen.

**Comment by Serhioromano** [comment]
I have added description to readme file for new users.

**Comment by K-Ko** [comment]
You mean e.g.

```
	...
	"version": "1.0.0",
	...
```

which will be updated on finish release/1.1.0 ?

> 3. ... before process finish command package.json will be updated to version 1.0.1

And makes a "Bumped version" commit **before** `git flow release finish release/1.1.0`?

Ok, this to late for me, because I need the version bump **before** finish.
The release branch will be deployed to QA and need to know the "new" version.

In gitex-flow extension it works like this:
1. release start and make the release branch
2. bump version `packages.json` in release branch
3. commit this file with message "Bumped version" in release branch

This is perfect, if the release branch passed QA, it can be finished as is.

**Comment by Serhioromano** [comment]
> And makes a "Bumped version" commit before git flow release finish release/1.1.0?

Exactly

> This is perfect, if the release branch passed QA, it can be finished as is.

Cool. That makes sense. I can change it. Tell me more what is changed in Changelog? `[unreleased]` or what placeholder to update to new version?

**Comment by K-Ko** [comment]
> Tell me more what is changed in Changelog?

Don't know how [gitex-flow](https://github.com/gitex-flow/gitex-flow-vscode) works in this case ...

CHANGELOG is not that important.

Yes, bump version **early** would be fine :-)

**Comment by Serhioromano** [comment]
I've changed and in new version 1.2.0 `package.json` version is bumped on release creation but not finish.

Also, I investigated about changelog and now update changelog too. Rules how it is done in the README file.

If you do not mind, please rate this extension here  
https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-gitflow&ssr=false#review-details
