### ISSUE TITLE
Finish a branch which creates a tag

### ISSUE THREAD

**Issue by K-Ko** [Serhioromano/vscode-gitflow#20]
**Feature request**

- Accept a given text on finish as the `-m` parameter value

**As is**

At the moment a fixed tag message is used and in the dropdown on finishing a branch the `-m` option is not available.

![image](https://user-images.githubusercontent.com/327396/156599718-bce139a4-df1f-4dba-8a99-45b37aad0fde.png)

If I put there some text, e.g. "Feature release" it is ignored and a fixed message "Finish ..." is generated:

![image](https://user-images.githubusercontent.com/327396/156599957-3e7d2ca5-ae3d-4f2d-a5ff-11b536492256.png)

(Did not checked yet what happen if I provide there a `-m "My message"`, may be it will accepted?)

**Comment by Serhioromano** [comment]
No. It will not work if you put there -m. I'll see if that can be done.bthis 8s quick pick and it returns array of preset elements. I can add another input box to enter message and prefill it. What do you think?

**Comment by Serhioromano** [comment]
Release 1.2.0 now allow you to enter message. Although I do not see where it appears. It is still an automatic message about a merge. But to pass message to gitflow is all I can do from my side.

**Comment by K-Ko** [comment]
I mean not the commit message, I mean the tag message.

The merge messages are fine:
![image](https://user-images.githubusercontent.com/327396/156718510-3992f1b3-a2e4-4205-9682-c2aefae14560.png)

But the tag becomes the "automatic" message:
![image](https://user-images.githubusercontent.com/327396/156718749-d6f751e8-12ca-4ee7-a562-a9d966a5f23a.png)

**Comment by Serhioromano** [comment]
This is what I say. I pass `-m` parameter to `git flow release finish`. It is there, because this command create a tag. But somehow it is not in the tree later. I do not know why. May be to report to git flow AVH project.

**Comment by K-Ko** [comment]
This is still fine:
![image](https://user-images.githubusercontent.com/327396/156726067-b9527c3a-d908-4953-a9a1-b82102d9a9c3.png)

But the `finish` command is executed with "undefined" message
```
INFO: [Run command] gitflow.finishHotfix
INFO: [Run command] gitflow.refreshT
INFO: [git flow hotfix finish  -m"undefined" -T "0.34.1" 0.34.1 ] Your branch is ahead of 'origin/master' by 4 commits.
```
![image](https://user-images.githubusercontent.com/327396/156726457-50d3c584-6809-4a44-9d68-32844e90293a.png)

**Comment by Serhioromano** [comment]
I could not reproduce it. But I created a patch anyway try new 1.2.5.

**Comment by K-Ko** [comment]
Made some test in a new repo.

# Feature

```
INFO: [Run command] gitflow.newFeature
INFO: [git flow feature start  test ] 
```
![image](https://user-images.githubusercontent.com/327396/156754431-6b5e5078-f462-43e8-a247-69f57f2ec4ba.png)

```
INFO: [Run command] gitflow.finishFeature
INFO: [git flow feature finish  test ] Already up to date.
```
Works also on ESC in popup

# Test `release`
without `package.json` yet
```
INFO: [Run command] gitflow.newRelease
INFO: [Run command] gitflow.refreshT
INFO: [git flow release start  0.1.0 ] 
```
Add package.json now
Give a message
![image](https://user-images.githubusercontent.com/327396/156756146-e4c2d26f-0f64-4a59-8657-31236d5701c8.png)
**BUT if I then press ESC and  also in the next pop (with the parameters) the release happens with `-m "undefined"`**
```
INFO: [Run command] gitflow.finishRelease
INFO: [Run command] gitflow.refreshT
INFO: [git flow release finish  -m"undefined" -T "0.1.0" 0.1.0 ] Merge made by the 'ort' strategy.
 package.json | 3 +++
 1 file changed, 3 insertions(+)
 create mode 100644 package.json
Merge made by the 'ort' strategy.
 package.json | 3 +++
 1 file changed, 3 insertions(+)
 create mode 100644 package.json
Deleted branch release/0.1.0 (was 231e849).
```
So after the ESC in the message popup the release will **not** canceled.

# Another release
```
INFO: [Run command] gitflow.newRelease
INFO: [git add ./package.json] 
INFO: [git commit ./package.json -m"Version bump"] [develop 4e9e63f] Version bump
 1 file changed, 1 insertion(+), 1 deletion(-)

INFO: [Run command] gitflow.refreshT
INFO: [git flow release start  0.2.0 ] 
Summary of actions:
- A new branch 'release/0.2.0' was created, based on 'develop'
- You are now on branch 'release/0.2.0'
```
But this is not correct from my point of view.
The version bump must be done in the **release** branch, **not** in develop!
Develop MUST stay on the "old" version, **only the release branch** may have the new version.

Assume this: the release will not approved and therefore canceled.
No problem, branch just can be deleted and recreated later.
**But** develop has the version bump, not good if I publish the develop branch!

So I think just swap the logic
- start release
- bump version

**Comment by Serhioromano** [comment]
Pin it for Monday. Too late already.

**Comment by Serhioromano** [comment]
Version 1.2.8 fixes

- Stop on ESC
- Version bump on release branch.

Once again, thank you for finding time to go through those bugs and describe them in so detailed. I very appreciate it.

**Comment by Serhioromano** [comment]
Although your experience with this extension is not as good as it could be, I would still appreciate if you rate this extension in marketplace.

**Comment by K-Ko** [comment]
Perfect, `v1.2.9` works as expected :-)

![image](https://user-images.githubusercontent.com/327396/157032560-519e7a0e-0f04-46b4-a50f-1d62a0d8a0d8.png)
