### ISSUE TITLE
extension Error: 'flow' is not a git command

### ISSUE THREAD

**Issue by EvStorM** [Serhioromano/vscode-gitflow#29]
Error executing: "/usr/bin/git" flow log : Error: Command failed: "/usr/bin/git" flow log
git: 'flow' is not a git command. See 'git --help'.
The most similar commands are
	reflog show
To use Git Flow extension please install Git flow (AVH).

**Comment by EvStorM** [comment]
I have installed git-flow
The terminal can run

**Comment by Serhioromano** [comment]
> I have installed git-flow

Can you give a link?

**Comment by Serhioromano** [comment]
@EvStorM I cannot find `git-flow` executable. Where did you install it from? Can you give a link?

**Comment by EvStorM** [comment]
In macos, git flow is an executable file with git files, but I don't know if Windows is still like this.
2022年5月17日 +0800 19:07 Sergey Romanov ***@***.***>，写道：

**Comment by Serhioromano** [comment]
@EvStorM  Is it there by default or you install it? If yes tell me how did you do that? I'll check it on mac.

**Comment by EvStorM** [comment]
Mac install git-flow-ach will have this file in the usr/local/bin directory.


	@EvStorM Is it there by default or you install it? If yes tell me how did you do that? I'll check it on mac.

**Comment by Serhioromano** [comment]
@EvStorM I wanted to accept your PR but it is not formatted properly. If you do not mind, I copied the changes you have proposed and inserted them into the extension manually. 

Your solution is nice. Thank you.

Next time if you want your PR be accepted by anyone, send PR with as little changes as possible. DO not reformat document and do not make changes of different features in one PR. Create separate branch from `develop` for each tiny feature. And create separate PR from separate branch.
