### ISSUE TITLE
Feature request: make current branch better visible

### ISSUE THREAD

**Issue by Lefthandmedia** [Serhioromano/vscode-gitflow#31]
I find it hard to spot which branch is current. Right now the label 'current' after the branchname often falls outside the panel with long branchnames.
So is it possible to give the current branch either a different color (green), or an icon in front of the branchname.
tnx
RDG

**Comment by Serhioromano** [comment]
Added icon Home. Will be there in the next update later this week. Thank you for your feature. Indeed small but useful.
