### ISSUE TITLE
replace SPACE with _ underscore

### ISSUE THREAD

**Issue by Lefthandmedia** [Serhioromano/vscode-gitflow#33]
Hi,

 When i start a new feature i ussualy give it a name prefixed with a number. Sourcetree is nice enough to replace the **spaces** in the branchname i hapen to type with **underscores**. Since spaces are illegal in branchnames apparantly
Vscode-gitflow does not do this. in fact it just does not create the branch at all without any feedback.
So when i create a branch in vscode-gitflow `MYPROJECT-12345_This is a stupid branch` i expect it to be changed to the legal branchname  `MYPROJECT-12345_This_is_a_stupid_branch` so it can and will be created.

tnx
RDG

**Comment by Serhioromano** [comment]
Done. Easy to fix. New version 1.3.9 has this fix. Please do not forget to rate this extension here
https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-gitflow&ssr=false#review-details

**Comment by mackelito** [comment]
It would be nice to have this separator in config.. I would like to have it named using - instead of _

**Comment by Serhioromano** [comment]
> It would be nice to have this separator in config.. I would like to have it named using - instead of _

Working on it. Will be in new version later today.
