### ISSUE TITLE
home git-flow and actual current branch differ

### ISSUE THREAD

**Issue by Lefthandmedia** [Serhioromano/vscode-gitflow#34]
Hi,
I see a difference in the home (current) branch in gitflow and in VScode git?
<img width="328" alt="gitflow" src="https://user-images.githubusercontent.com/3350108/169484575-c69328e6-733c-4e7f-ad2e-51497c12ffec.png">

**Comment by Serhioromano** [comment]
I have not yet found a way to update tree view when you checkout new branch through VS Code features. If you checkout though that feature, you need to refresh Git Flow view. Or switch branches in Git Flow view.
