### ISSUE TITLE
command 'gitflow.quickPick' not found

### ISSUE THREAD

**Issue by Systemgeek-louis** [Serhioromano/vscode-gitflow#39]
Just installed version 1.3.11 on VS Code 1.69.2 on my mac 12.5 (Intel).

When I click on Git Flow on the bottom blue bar I get a popup that says: command 'gitflow.quickPick' not found.

How do I fix this?
I do have gitflow installed and use it from the mac terminal all the time.  And I have set the gitflow.path in setting.

**Comment by Serhioromano** [comment]
Do you see Gitflow panel like this?

![2022-08-04_11-38-33](https://user-images.githubusercontent.com/650741/182771057-1369f3e2-a9f4-46a3-8280-2b5fb8fb273f.png)

**Comment by Systemgeek-louis** [comment]
I never saw anything under GITFLOW.  This is what I see:

Louis

**Comment by Serhioromano** [comment]
What if you open terminal in the root of your project and run `git flow list` command? If there is no list of repositories then run `git flow init` command and restart VS Code.

**Comment by Serhioromano** [comment]
Any news? Is it working?

**Comment by Systemgeek-louis** [comment]
No news.  Nothing has changed that I can tell except Visual Studio is now at 1.70.0.  Gitflow in SCM Side bar still shows blank and I keep getting the error:  Error executing: "/usr/local/bin/git" status : Error: Command failed: "/usr/local/bin/git" status fatal: not a git repository (or any of the parent directories): .git
Which is very odd because the rest of SCM sees it as a git repo.  I even went in to this specific repo and ran git init and took all the defaults and then restarted SCM.  Going back in to SCM and this repo I am still getting that message.

Louis

**Comment by Systemgeek-louis** [comment]
I just went through all my repos and performed the following actions on all of them:
git init on all of them from the command line (the Mac terminal not the SCM terminal)
verified all the repos with git flow feature list
Restarted SCM

In SCM I clicked on Explorer and picked one of the repos.  Got the following error 


Louis

**Comment by Serhioromano** [comment]
There was a light bug in 1.3.12 that made ` Error executing: "/usr/local/bin/git" status` error. Please update 1.3.13 and try once more.
