### ISSUE TITLE
Label features and co

### ISSUE THREAD

**Issue by tguenneguez** [Serhioromano/vscode-gitflow#4]
In a label of feature, the allow caractères are only [a-z] and -.
It shoud be display when you ask for it ?

**Comment by Serhioromano** [comment]
Pardon? Did not get the question. Where display? What to display?

**Comment by tguenneguez** [comment]
Oups, i have not read.
The dot char is allow in some type of label but not for all.
It will be eassyer to replace space to underscore automaticly ?

**Comment by Serhioromano** [comment]
That is the right question. It might be acceptable for some people but other might like hyphen. I think best way is just validate input.

**Comment by Serhioromano** [comment]
> Oups, i have not read. The dot char is allow in some type of label but not for all. It will be eassyer to replace space to underscore automaticly ?

I have refactored code from 1800 lines to 580 in latest version 1.5.1. In that release I select name in one place with single regEx pattern for all branch types.
