### ISSUE TITLE
Startup takes too long

### ISSUE THREAD

**Issue by romanholidaypancakes** [Serhioromano/vscode-gitflow#40]
- Issue Type: `Bug`
- Extension Name: `vscode-gitflow`
- Extension Version: `1.3.11`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.2`

![image](https://user-images.githubusercontent.com/16742566/183254022-955b2fc4-65f6-40ca-b09a-bbb378c31e52.png)

**Comment by Serhioromano** [comment]
There might be few reasons for that. Can you look in OUTPUT-> Gitflow and copy log from there to here. There is a time for each command I'll know which one takes the most time.

**Comment by Serhioromano** [comment]
These are commands that takes long time. 

```
"C:\Program Files\Git\cmd\git.exe" status
"C:\Program Files\Git\cmd\git.exe" flow log
```

Can you run those in terminal in your repository directory and see how long it takes?

Another long command is

```
"C:\Program Files\Git\cmd\git.exe" remote
```

But that is understandable, it fetches from remote and it depends on internet speed.

**Comment by Serhioromano** [comment]
I published new version and change `git flow log` to `git flow status`. Should work faster. еest it 1.3.12

**Comment by Serhioromano** [comment]
Check version 1.3.13

**Comment by Serhioromano** [comment]
You have any configuration for git path?

**Comment by Serhioromano** [comment]
I also have this error but I can see elements in side bar. Do you?

**Comment by Serhioromano** [comment]
You see viewlet title or branches inside it?

**Comment by Serhioromano** [comment]
I cannot find the reason of a long load apart from remote request. ше also require Git panel to lad before it starts to load at all.
