### ISSUE TITLE
After latest release/1.3.16 I don't see anything in tabs

### ISSUE THREAD

**Issue by kova1max** [Serhioromano/vscode-gitflow#42]
After updating extention to `v1.3.16` I have noticed that tabs `SOURCE CONTROL: GITFLOW` & `SOURCE CONTROL: VERSIONS` are both empty. To make extention working again I had to decrease version of extention to `v1.3.15`.
![image](https://user-images.githubusercontent.com/32361852/187167590-28d28009-645a-4a30-b9f8-2d97199250e1.png)

**Comment by Serhioromano** [comment]
That is right. Thank you. fixed already 1.3.17. Please do not forget to rate extension [here](https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-gitflow&ssr=false#review-details)
