### ISSUE TITLE
Making this extension available on OpenVSX marketplace

### ISSUE THREAD

**Issue by glamax13** [Serhioromano/vscode-gitflow#44]
First thank you for this great extension!

I have been using your extension with VsCode on my work hours and really enjoying it.
But i like to keep my personal computer free with only OSS software so I prefer to use VsCodium (an OSS fork of VsCode).
The thing is that VsCodium uses OpenVSX as a marketplace (because Microsoft limits the uses of it's marketplace to VsCode only).

So i was wondering if you would be open to make it available on this alternate marketplace.
It is supposed to be pain free but i haven't actually tried it or anything soooo i'm no one to tell.
[Here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) is the documentation on how to proceed if you are interested.
There is also a [bot](https://github.com/open-vsx/publish-extensions) that update the packages nightly.

I'll try to help you in any way i can.
Thank you for your time!

**Comment by Serhioromano** [comment]
I have published this extension on OVSX. And I added an automation that will update that extension every time I release a new version. Please, rate my extension on OVX please.

https://open-vsx.org/extension/Serhioromano/vscode-gitflow

And in marketplace 

https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-gitflow&ssr=false#review-details

**Comment by glamax13** [comment]
That was fast!
I already rated it on VsCode marketplace yesterday as prompted by your bot but i will happily make one for OVSX.

Thanks a lot and best of luck to you.

**Comment by glamax13** [comment]
It seems like i cannot yet rate the extension on OpenVSX.
It appears that there is an issue regarding the namespace "Serhioromano" that may be the reason that prevent me to do it.

The full warning is:
>This version of the “Git Flow” extension was published by [Serhioromano](https://github.com/Serhioromano). That user account is not a verified publisher of the namespace “Serhioromano” of this extension. [See the documentation](https://github.com/eclipse/openvsx/wiki/Namespace-Access) to learn how we handle namespaces and what you can do to eliminate this warning.

**Comment by Serhioromano** [comment]
> It seems like i cannot yet rate the extension on OpenVSX. It appears that there is an issue regarding the namespace "Serhioromano" that may be the reason that prevent me to do it.
> 
> The full warning is:
> 
> > This version of the “Git Flow” extension was published by [Serhioromano](https://github.com/Serhioromano). That user account is not a verified publisher of the namespace “Serhioromano” of this extension. [See the documentation](https://github.com/eclipse/openvsx/wiki/Namespace-Access) to learn how we handle namespaces and what you can do to eliminate this warning.

Yes, I have claimed namespace and I do not know how long that could take to approve. Please come back to it in few days if you have time.

**Comment by Serhioromano** [comment]
> That was fast! I already rated it on VsCode marketplace yesterday as prompted by your bot but i will happily make one for OVSX.
> 
> Thanks a lot and best of luck to you.

Thank you for your Marketplace review. That one was very nice to read.

**Comment by Serhioromano** [comment]
> It seems like i cannot yet rate the extension on OpenVSX. It appears that there is an issue regarding the namespace "Serhioromano" that may be the reason that prevent me to do it.
> 
> The full warning is:
> 
> > This version of the “Git Flow” extension was published by [Serhioromano](https://github.com/Serhioromano). That user account is not a verified publisher of the namespace “Serhioromano” of this extension. [See the documentation](https://github.com/eclipse/openvsx/wiki/Namespace-Access) to learn how we handle namespaces and what you can do to eliminate this warning.

Namespace was confirmed. You can rate it now.
