### ISSUE TITLE
Support git hooks like gitflow-avh 

### ISSUE THREAD

**Issue by jclaveau** [Serhioromano/vscode-gitflow#47]
gitflow-avh adds git hooks based on feature / bugfixes...: 
- https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Hooks-and-Filters#hooks
- https://github.com/petervanderdoes/gitflow-avh/tree/develop/hooks

I personally use it to forbid `git flow feature finish` to force the developers to create a PR on Github as recommended here https://stackoverflow.com/a/64436619/2714285

Triggering those hooks from your extension would be really nice to ensure the CI/CD pipe is followed (no merge in develop without a valid PR)

Anyway, thank you for your work!

**Comment by Serhioromano** [comment]
Thank you for pointing to this feature. I di dnot know aout this. But as I understand from documentation Hooks is a simple naming convention. All you need to do is create a hook with exact file name structure and it will be triggered no matter run with my extension of command line.

So you can use it now I think.

**Comment by jclaveau** [comment]
Ow. It tried it just before opening this issue and the finish passed. I can't figure out why but, anyway, it now works (almost) as expected.

I have the following `pre-flow-feature-finish` hook (configured with Husky):
```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Please use a Github's pull request to merge your patch following the CICD pipe"
exit 1
```

Then when I press the "feature finish" button from your extension I get the following error.

![image](https://user-images.githubusercontent.com/1556489/205928657-a6db551e-5b65-4688-9136-ec2a1579f7d1.png)
 

You may consider it as over-engineered but displaying stdout / stderr in the error message would be really practical.


Anyway, thank you for your fast response and your work!

**Comment by Serhioromano** [comment]
Consider to add a rating for this extension. That would help a lot.
https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-gitflow&ssr=false#review-details

Also I have a question. If I add hooks in `.git/hooks` folder will it sync across all repositories or work only inside my own repository? As I understand those files will not be committed and pushed right?

**Comment by jclaveau** [comment]
> Consider to add a rating for this extension. That would help a lot. https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-gitflow&ssr=false#review-details

Thank you for the reminder, I gave you a 5 stars as all others, great job!

> Also I have a question. If I add hooks in `.git/hooks` folder will it sync across all repositories or work only inside my own repository? As I understand those files will not be committed and pushed right?

Your right: Git doesn't allow committing git hooks

This is exactly the purpose of [Husky](https://typicode.github.io/husky/#/) (for JS/TS projects at least):
+ It stores your hooks in the /.husky folder
+ Then adding `"postinstall": "node -e \"process.env.NODE_ENV != 'production' && process.exit(1)\" || yarn husky install"` to the `package.json` file will enable it for all your team while running `yarn install` in non production environment

This is the only way I found to integrate well a Github CI/CD with Gitflow and your extension adds a great UI/UX for that, especially juniors

**Comment by Serhioromano** [comment]
Remarkably interesting I did not know about Husky. Thank you. I'll see how this could be integrated into my flow and eventually, perhaps to extension :)

**Comment by jclaveau** [comment]
Some tips:
+ force lint / test run before commit/push
+ autogenerate the Pull/Merge request in Github/Gitlab at `feature publish`
+ close PR when `feature delete` if published...
+ forbid the merge into dev branch during `feature finish"
+ Forbid commit/push to `main`
+ Maybe (i've never tested) force "pull --rebase" instead of merges

Have fun!
