### ISSUE TITLE
Set Tag name on finish Release or HotFix

### ISSUE THREAD

**Issue by freemiumdev** [Serhioromano/vscode-gitflow#52]
hi,
with git command in terminal when i finish a release or hotfix i can specify the tag name with parameter -T or --tagname

Is possibile with this extension?

thanks

**Comment by Serhioromano** [comment]
Yes it is. the best practice for a release or hotfix to give it a name like 1.2.3 so when you finish it becomes the name of the tag. Although during Finish process you may change the name of the tag.
