### ISSUE TITLE
Error executing `git-flow config list` command

### ISSUE THREAD

**Issue by alexmf91** [Serhioromano/vscode-gitflow#55]
**Summary**:
I'm encountering an error while using the "GitFlow" extension in Visual Studio Code. When I try to execute the `git-flow config list` command, it fails with the following error message:

```
ERROR: (61ms) [/opt/homebrew/bin/git-flow config list] ERROR: Error: Command failed: /opt/homebrew/bin/git-flow config list
```

**Environment**:
- Operating System: [e.g., macOS Big Sur 11.5.1]
- Visual Studio Code version: [e.g., 1.60.1]
- Git version: [e.g., 2.39.2 (Apple Git-143)]
- "GitFlow" extension version: [e.g., 1.0.0]

**Steps to Reproduce**:
1. Install and activate the "GitFlow" extension in Visual Studio Code.
2. Open a project with Git version control initialized.
3. Run the `git-flow config list` command.

**Expected Behavior**:
The `git-flow config list` command should execute successfully and display the Git-Flow configuration details.

**Actual Behavior**:
The command fails to execute, and the error message mentioned above is shown in the output.

**Additional Information**:

- The path to the `git-flow` binary is correctly set in the extension settings as `/opt/homebrew/bin/git-flow`.
- The `git-flow` binary is installed and executable in the specified path.

**Screenshots**:
If applicable, please attach any relevant screenshots that might help in understanding the issue.

**Additional Context**:
I've already tried the following troubleshooting steps:
- Updating the extension to the latest version.
- Verifying that the path to the `git-flow` binary is set correctly.
- Checking for compatibility between the extension, Git version, and `git-flow` version.
- Restarting Visual Studio Code after making configuration changes.

Despite these efforts, the issue persists. I'm unable to use the `git-flow` commands through the extension.

Any assistance or insights into resolving this problem would be greatly appreciated.

**Comment by Serhioromano** [comment]
Hello,

`/opt/homebrew/bin/git-flow` is not my piece of tech. It is created by other people. My extension just uses this command line tool. If you cannot run commands of `git flow` in a terminal, my extension will not work. Unfortunately, I cannot debug git flow CLI tool for it is written in bash, which is outside of my scope of expertise.

**Comment by bkmeneguello** [comment]
I had the same issue. looks like this extension is based on the archived [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh) instead of the currently active [gitflow](https://github.com/nvie/gitflow)

**Comment by Serhioromano** [comment]
> I had the same issue. looks like this extension is based on the archived [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh) instead of the currently active [gitflow](https://github.com/nvie/gitflow)

Currently active? Last commmit 12 years ago. AVH 5 years ago.
