### ISSUE TITLE
Feature request : Add option to turn off `git flow init` prompt 

### ISSUE THREAD

**Issue by iommu** [Serhioromano/vscode-gitflow#57]
As someone who works on a lot of projects which don't use the `git flow` structure it would be nice to have a vscode setting (for global and workspace) to disable the notification from popping up on every vscode startup.

Example of the notification in question:
![image](https://github.com/Serhioromano/vscode-gitflow/assets/11268243/48e75dd5-24b8-40f9-bb1b-60e057628a26)

**Comment by Serhioromano** [comment]
Added to new 1.3.24 update. PLease check. Do not forget to rate.
