### ISSUE TITLE
Missing icons on hover for features in the Gitflow view

### ISSUE THREAD

**Issue by EdenChar** [Serhioromano/vscode-gitflow#58]
There are **no icons to click** when hovering over the **`features`** in the **Gitflow view** like there are for **`releases`**,  **`hotfix`**, ...
Therefore, in order to **finish a feature**, you have to **`ctrl-shift-p`** + **`Git-flow: Feature - finish`**.
It's not really a big deal to not have the icons, but they would make the process even easier.

**Comment by Serhioromano** [comment]
I cannot reproduce this behavior. Also note there is `Shift`+`Alt`+`D` quick pick menu. Faster that ctrl-shift-p and search for a command
