### ISSUE TITLE
Quick pick menu not updating the options

### ISSUE THREAD

**Issue by msousafedrax** [Serhioromano/vscode-gitflow#65]
After creating a release we need to close it but the quick pick menu is not showing the correct options.
I started a new release here
![image](https://github.com/user-attachments/assets/f005f69a-7c13-4366-93d2-dca2c3c79faf)
And everything is ok, I can see the release was created and I am on the release branch 
![image](https://github.com/user-attachments/assets/a9aad97a-0dfc-4094-9a39-3a61b1512e00)
I updated the Changelog and now I want to finish the release but there is no option to finish the release
![image](https://github.com/user-attachments/assets/4ddbe716-9d6e-4af6-8cb4-77f27628bedb)
If I do a reload of the window I can see the correct options
![image](https://github.com/user-attachments/assets/563cce97-e3dd-4c2c-8722-ed6502b10560)

Thank you

And last but not least thank you for this great extension.

**Comment by Serhioromano** [comment]
Hi, it has just happened that I am working on a new release. And I tested your issue. Unfortunately I cannot reproduce this behavior. It works fine for me. Perhaps it is some local issues may be untrusted folder or some browser settings.

**Comment by msousafedrax** [comment]
> Hi, it has just happened that I am working on a new release. And I tested your issue. Unfortunately I cannot reproduce this behavior. It works fine for me. Perhaps it is some local issues may be untrusted folder or some browser settings.
Thank you for your answer could it be because I'm on WSL ?

**Comment by Serhioromano** [comment]
> > Hi, it has just happened that I am working on a new release. And I tested your issue. Unfortunately I cannot reproduce this behavior. It works fine for me. Perhaps it is some local issues may be untrusted folder or some browser settings.
> 
> Thank you for your answer could it be because I'm on WSL ?

I do not think so. I am also on remote WSL.
