### ISSUE TITLE
Pb with space in the local directory

### ISSUE THREAD

**Issue by tguenneguez** [Serhioromano/vscode-gitflow#8]
When there is a space un the local directy, the git init failed

```
PS ....\visual studio Code> cd c:\Users\DXPC9379\visual studio Code\projet
Set-Location : Impossible de trouver un paramètre positionnel acceptant l'argument « studio ».
Au caractère Ligne:1 : 1
+ cd c:\Users\DXPC9379\visual studio Code\projet ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
 
PS ....\visual studio Code> git flow init -f
Fatal: Working tree contains unstaged changes. Aborting.
```

**Comment by Serhioromano** [comment]
The actual error is `Fatal: Working tree contains unstaged changes. Aborting.`. You have to commit all changes first.

**Comment by tguenneguez** [comment]
Yes but the firs error is 👍 cd c:\Users\DXPC9379\visual studio Code\projet
Set-Location : Impossible de trouver un paramètre positionnel acceptant l'argument « studio ».
There is a space in the directory
So the commande is not execute in the good directory.

**Comment by Serhioromano** [comment]
Di you кен to commit all changes? Did it solve problem?

**Comment by tguenneguez** [comment]
To solve the problem, I go manualy in the directory and run the command.

**Comment by Serhioromano** [comment]
Do you use WSL?

**Comment by tguenneguez** [comment]
What is WSL ?

**Comment by Serhioromano** [comment]
You run VS Code on windows, right? Do you have WSL on your windows machine? If you do not know what it is most [probably you do not. But I would strongly recommend to investigate this if you are developer.

**Comment by tguenneguez** [comment]
I haven't

**Comment by Serhioromano** [comment]
I try to solve it. I made few changes. Can you manually install extension and test if error is gone?

[vscode-gitflow-0.5.10.zip](https://github.com/Serhioromano/vscode-gitflow/files/7999947/vscode-gitflow-0.5.10.zip)
